var l,q="undefined"==typeof browser,t=0<navigator.userAgent.indexOf("Edge/"),w=0<navigator.userAgent.indexOf("Firefox/"),aa=0<navigator.userAgent.indexOf("OPR/");q&&(browser=chrome);t&&(browser.app=chrome.app);
var ba=w?69:t?77:66,ca=w?220:150,x=[atob("MTI3LjAuMC4xOjEwMDE="),atob("MC4xLjAuMToxMDAx")],da=atob("cGx1Z2luLnYzLmludGVybmV0ZG93bmxvYWRtYW5hZ2VyLmNvbQ=="),ea=atob("djYuMjZiMTQ="),fa=atob("djYuMjg="),ga=atob("bmdwYW1wYXBwbm1lcGdpbG9qZm9oYWRoaG1iaGxhZWs="),ha=atob("amVhb2hobGFqZWpvZGZqYWRjcG9ucG5qZ2tpaWtvY24="),ia=atob("YWZtZHBtZGRpb2twZGtuYWVvZmRubGNsYnBnZWhoY2U="),ja=atob("Q2hyb21lX1JlbmRlcldpZGdldEhvc3RIV05E"),ka=["main_frame","sub_frame"],y="main_frame sub_frame image object xmlhttprequest other".split(" "),
A=["image","object","xmlhttprequest","other"],la=["origin","referer"],ma=[301,302,303,307],na=["*://*/*","ftp://*/*","file:///*"],B=["http://*/*","https://*/*"],oa=/\.([^.\\/]*?)(?:\.[0-9.]+)?$/,pa=browser.runtime.getURL("captured.html"),qa=browser.runtime.getURL("").slice(0,-1),ra=browser.extension.getBackgroundPage().location.href,sa=/(?:chrome|about|chrome-extension|ms-browser-extension|moz-extension):/,ta=[atob("KjovLyouaW50ZXJuZXRkb3dubG9hZG1hbmFnZXIuY29tL2F1dG9yZWcuaHRtbD8q"),atob("KjovLyouaW50ZXJuZXRkb3dubG9hZG1hbmFnZXIuY29tL2ZpbGxyZWdmb3JtLmh0bWw/Kg==")],
ua=new RegExp(atob("Xig/Omh0dHB8aHR0cHMpOi8vKD86d3d3XC55b3V0dWJlXC5jb20vKD86d2F0Y2hcP3xlbWJlZC8pfHd3d1wuZmFjZWJvb2tcLmNvbS8oPzouKy8oPzp2aWRlb3N8cG9zdHN8cGVybWFsaW5rKS8oPzpcdytcLlxkKy8pP1xkK1xifHZpZGVvL1x3Ky9hc3luY1xifHZpZGVvL2VtYmVkXGIpfHBsYXllclwudmltZW9cLmNvbS92aWRlby9cZCsp"),"i"),va=new RegExp(atob("Xig/Oltcd1wtXStcLikqPyg/OnlvdXR1YmVcLmNvbXxnb29nbGV2aWRlb1wuY29tfHlvdXR1YmVcLmdvb2dsZWFwaXNcLmNvbXxkb2NzXC5nb29nbGVcLmNvbSkk"),"i"),wa=atob("L3ZpZGVvcGxheWJhY2s="),xa=atob("L2dldF92aWRlb19pbmZv"),ya=
atob("L2FwaV92aWRlb19pbmZv"),za=atob("L2FwaS90aW1lZHRleHQ="),Aa=atob("L2FwaS9tYW5pZmVzdC9kYXNo"),Ba=new RegExp(atob("Xig/Oltcd1wtXStcLikqPyg/OnZpbWVvXC5jb218dmltZW9jZG5cLmNvbSkk"),"i"),Ca=atob("cGxheWVyLnZpbWVvLmNvbQ=="),Da=atob("L3ZpZGVvLw=="),Ea=new RegExp(atob("Xig/Ond3d1wuZmFjZWJvb2tcLmNvbXwoPzpbXHdcLV0rXC4pKj9mYmNkblwubmV0KSQ="),"i"),Fa=new RegExp(atob("Xi92aWRlby9cdysvYXN5bmMvKFxkKykv")),Ga=new RegExp(atob("Lyg/Oi4rLyg/OnZpZGVvc3xwb3N0c3xwZXJtYWxpbmspLyg/Olx3K1wuXGQrLyk/fHZpZGVvL2VtYmVkXD8uKj9cYnZpZGVvX2lkPSkoXGQrKVxi")),
Ha={16:1,17:2,18:4,45:8,46:16},Ia={http:1,https:129,ftp:2,ftps:130,rtmp:3,rtmpt:3,rtmpe:3,mms:4,idmreg:159},Ja={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|SRT","text/srt":"SRT","text/vtt":"VTT|SRT","text/xml":"XML|F4M|TTML","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/f4m+xml":"F4M","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/pdf":"PDF",
"application/ttaf+xml":"DFXP","application/vnd.apple.mpegurl":"M3U8","application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-dosexec":"EXE","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI","application/x-msp":"MSP",
"application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|M3U8","video/mp4":"MP4|M4V","video/mpeg":"MPG|MPEG",
"video/mpegurl":"M3U|M3U8","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U|M3U8","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp3":"MP3","audio/mp4":"M4A|MP4","audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8",
"audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U|M3U8","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};function C(){this.b=this.constructor.prototype.c++}C.prototype.c=1;
function Ka(a,b,c,d){this.id=a;this.port=b;c&&(this.b=c.toLowerCase());d&&(this.url=d)}Ka.prototype.a=0;function La(a,b,c){this.id=[a,b].toString();this.b=0>c?null:[a,c].toString()}
function D(a,b,c,d,e,f){if(a){var h=["MSG#",a,"#",b,"#",c,"#",d];this.g=a;this.f=b;this.i=c;this.h=d;this.a=e||[];this.j=h;if(e)for(a=0;a<e.length;a++)h.push(":",e[a]||0);if(f)for(var g in f)if(e=f[g],null!=e)if(h.push(",",g,"="),"string"==typeof e){b=a=e.length;for(c=0;c<b;)d=e.charCodeAt(c++),128<=d&&(2048<=d?(a+=2,d-55296&56320||c++):a++);h.push(a,":",e)}else e instanceof Blob?h.push(e.size,":",e):h.push(e)}else this.c=new FileReader}
function Ma(a){a.W||(a.j.push(";"),a.W=!0);return new Blob(a.j)}function Na(a,b,c){a.W?a.w(a):(b.a=c||0,b.b=0,a.c.onload=a.Oa.bind(a,b),F(a,b,0,50))}l=D.prototype;
l.Oa=function(a){for(var b=this.c.result;;)switch(a.b){case 0:var c=b.split(",",2),d=c.shift().split(":",2),e=d.shift();if(!d.length){if(!c.length)return this.w(this);a.b=1}var f=e.length+1,d=e.split("#",6);if(5!=d.length||"MSG"!=d[0])return this.w(this);this.g=parseInt(d[1]);this.f=parseInt(d[2]);this.i=parseInt(d[3]);this.h=parseInt(d[4]);b=b.slice(f);a.a+=f;a.b++;break;case 1:d=b.split(",",2);e=d.shift();if(!d.length){d=b.split(";",2);if(2>d.length)return F(this,a,b.length,100);a.b=4}f=e.length+
1;this.a=d=e.split(":");for(e=0;e<d.length;e++)c=d[e],d[e]=c.includes(".")?parseFloat(c):parseInt(c);b=b.slice(f);a.a+=f;a.b++;break;case 2:c=b.split(",",2);2>c.length&&(c=b.split(";",2));var d=c.shift().split(":",2),h=d.shift(),f=h.length,e=!1;if(d.length)f++;else{if(!c.length)return F(this,a,b.length,25);e=!0}d=h.split("=",3);if(2!=d.length)return this.w(this);c=parseInt(d[0]);d=parseInt(d[1]);a.a+=f;a.b++;if(e){this[c]=d;b=b.slice(f);a.b++;break}a.f=c;a.c=d;b=a.c;f=a.a;a=a.slice(f,f+b);a.size==
b?this.c.readAsText(a):this.w(this);return;case 3:return this[a.f]=b,a.a+=a.c,a.b++,F(this,a,0,21);case 4:switch(b[0]){case ",":a.b=2;b=b.slice(1);break;case ";":a.b++;break;default:return this.w(this)}a.a++;break;case 5:this.W=!0;this.U(this);a.size>a.a&&(b=new D,b.U=this.U,b.w=this.w,Na(b,a,a.a));return}};function F(a,b,c,d){var e=b.a;c=e+c;b.size>c?a.c.readAsBinaryString(b.slice(e,c+d)):a.w(a)}l.m=null;l.U=null;l.w=null;l.W=!1;
function G(){var a=this.constructor.prototype,b;for(b in a)b.startsWith("_")||"constructor"==b||(this[b]=a[b].bind(this));b=navigator.userAgent;a=b.match(/\b(?!(?:Safari|Chrome|Gecko)\/)\w+\/(\d+)(?:.(\d+))?(?:.(\d+))?(?:.(\d+))?\b(?!.*[()])/);if(b=w?a:b.match(/\bChrome\/(\d+)\.(\d+)\.(\d+)\.(\d+)\b/)){this.j=b[1]<<24|b[2]<<22|b[3]<<8|b[4];this.ua=b[0];this.oa=a?a[0]:b[0];this.sa=[];this.O=!1;this.c={};this.v={};this.a={};this.i={};this.b={};this.l={};this.f={};this.g={};this.H={};this.Z="";this.$=
!0;this.Ka=this.ta=this.Ja=1;this.D={};this.h=null;this.X=1;this.u=!1;this.L=0;this.pa=null;this.qa=this.A=!1;this.N=0;this.ra=null;this.Y=this.M=!1;q&&browser.browserAction.disable();browser.windows.onCreated.addListener(this.Ca);browser.windows.onRemoved.addListener(this.Da);browser.windows.onFocusChanged.addListener(this.ab);browser.tabs.onActivated.addListener(this.Va);browser.tabs.onUpdated.addListener(this.Xa);browser.tabs.onAttached&&browser.tabs.onAttached.addListener(this.Wa);a=browser.runtime.getBrowserInfo;
b=browser.webRequest.ResourceType;a&&a(this.bb);b&&b.MEDIA&&y.push("media")&&A.push("media");w&&y.push("object_subrequest")&&A.push("object_subrequest");try{browser.windows.getAll({windowTypes:["normal","popup"]},this.ya)}catch(c){browser.windows.getAll(this.ya)}try{w&&browser.privacy.websites.firstPartyIsolate.get({},function(a){this.qa=a.value}.bind(this))}catch(c){}this.ba();Oa(this,!0)}}l=G.prototype;
l.bb=function(a){var b=a.version.split(/\D+/);this.j=b[0]<<24|b[1]<<22|b[2]<<8|b[3];this.ua=this.oa=a.name+"/"+a.version};function Oa(a,b){var c=a.c,d=a.D={};browser.contextMenus.removeAll();for(var e=0;e<Pa.length;e++){var f=Pa[e];f[0]&&(w?b||c[f[1]]:1)&&(d[e]=browser.contextMenus.create({title:Qa(f[2]),contexts:f[3].split(","),onclick:f[4].bind(a),documentUrlPatterns:f[5]||na,enabled:!0}))}}function Ra(a,b,c,d,e){a=a.f;return b in a?a[b]:a[b]=new Ka(b,c,d,e)}
function H(a,b){var c=a.g,d=b.requestId;c[d]=b;var e=b.id;e||(e=b.id=t?a.Ka++:d);e!=d&&(c[e]=b,c=a.i[[b.tabId,b.frameId]])&&(c.a=e)}function Sa(a){var b=new C;return a.l[b.b]=b}function I(a,b){var c=a.l[b];c&&delete a.l[b];return c}l.ba=function(){var a=new WebSocket("ws://"+x[this.L%x.length]+"/?cid="+Math.random().toString().substr(2,9),da);this.va=a;a.onopen=this.Ba;a.onclose=this.fa;a.onmessage=this.Ua;1==a.readyState?this.Ba():3==a.readyState&&this.fa()};
l.Ba=function(){this.u=!0;this.ta=1;var a={};a[112]=this.oa;a[113]=this.ua;a[114]=ja;if(587202560<=this.j){var b=browser.i18n.getUILanguage().replace("_","-");"sr"==b&&(b+="-Cyrl-CS");a[116]=b}J(this,2,0,[4,5,7,0],a)};
l.fa=function(){this.va=null;if(this.u){this.u=!1;this.H={};for(var a=this.sa,b=0;b<a.length;b++){var c=a[b],d=c.splice(0,2).pop();a.splice(b--,1);t&&c.splice(1);d.removeListener.apply(d,c)}this.O=!1;q&&browser.browserAction.disable()}a=++this.L;b=x.length;c=a/b;120>c&&(1==c&&this.$&&this.aa(),!a||a%b?this.ba():window.setTimeout(this.ba,5E3*c))};l.Ua=function(a){var b=new D;b.U=this.Qa;b.w=this.fa;Na(b,a.data)};
function J(a,b,c,d,e){if(!a.u)return!1;var f=a.ta++;b=new D(f,b,1,c,d,e);a.va.send(Ma(b));c&1&&(a.H[f]=b);return!0}
function Ta(a,b){var c=a.g;if(b.a){var d=b.a[6],e=d&&c[d];if(e){var f=e.type;return!f||"image"==f||e.c?(b.m=e.port.id,b.l=d,!0):!1}}var h=a.a,g=a.f,k=b[6],m=b[17],n=b[50],p=b[7],v,u;for(d in c){var e=c[d],r=e.url;if(r){if(r==k||r==m)if(f=e.type,!f||"image"==f||e.c)return b.m=e.port.id,b.l=parseInt(d),!0;r==n&&(u=e.port.id)}}for(d in g)if(c=g[d],r=c.url){if(r==k||r==m||r==n)if(e=c.port,p&&(f=h[e.tabId])&&f.url!=p&&(e=null),e)return b.m=e.id,!0;r==p&&(v=c.port.id)}return null!=u?(b.m=u,!0):null!=v?
(b.m=v,!0):!1}l.xa=function(a,b,c,d){if(b)return d?(b=(c=d.shift())&&this.a[c.id])?a.m=b.id:null:null;if(null!=a.m)return a.m;if(a.a){var e=a.a[7];if(e&&this.v[e])return a.m=e}if(Ta(this,a))return a.m;d=this.v;var f=a[50],h=a[7];for(e in d){b=d[e];if(b.url==f){a.m=e;break}null==a.m&&b.url==h&&(a.m=e)}if(null!=a.m)return a.m;h&&browser.tabs.query({url:h},K(this,a,!0,c));return null};
l.da=function(a,b,c,d,e){var f=a.tabId,h=a.frameId,g=a.windowId,k;if(void 0===b&&(b=new L(this,a,!0),null==g&&(a.a?(browser.tabs.get(f,M(b,2)),browser.windows.getLastFocused(M(b,3))):(g=this.a[f],a.windowId=g&&g.windowId)),null==h&&a.url&&browser.webNavigation.getAllFrames({tabId:f},M(b,4)),b.c()))return;c&&0<=c.index?a.windowId=c.windowId:d&&(a.windowId=d.id);if(e)for(d=e.length-1;0<=d;d--)if(c=e[d],!c.cb&&c.frameId&&c.url==a.url){h=a.frameId=c.frameId;k=c.parentFrameId;break}null==h?a.url||a.postMessage([11,
f,null,!0,a.b]):(e=[f,h].toString(),c=this.i[e],this.a[e]=a,0<=k&&(a.c=[f,k].toString()),c&&(a.i=c.a,a.b=c.c,(k=c.F)&&a.url!=k&&(a.F=k),!a.c&&c.b&&(a.c=c.b)),a.postMessage([11,f,h,!a.url,a.b]))};l.S=function(a,b,c,d,e,f,h){var g=N(a,!0);if(!g)return 0;if(1==g){if(!f)return O(this,a,K(this,a,b,c,d,e,!0)),-1;"object"==typeof h&&(h=P(h))}f=[g];g={};g[6]=a;g[8]=c;g[100]=d;g[102]=e;g[51]=h;g[54]=navigator.userAgent;g[7]=b;J(this,14,0,f,g);return 3};
l.Ga=function(a,b,c,d,e){if(!d){if(!a||!a.length)return;c||(c={});var f=new L(this,a,b,c,!0);c.Ia&&!c.Ea&&O(this,c.Ia,M(f,4));for(var h=0;h<a.length;h++)O(this,a[h][0],M(f,5+h));if(f.c())return}e&&(c.Ea=P(e));for(h=0;h<a.length;h++)a[h][5]=P(arguments[h+5]);var f=0,h=[a.length],g={8:4};g[54]=navigator.userAgent;g[7]=c.Ia;g[110]=c.G;g[111]=c.Ea;1<a.length&&(J(this,15,f,h,g),f=16,g={});for(var h=[0],k;k=a.shift();)g[6]=k[0],g[100]=k[2],g[102]=k[3],g[50]=k[4],g[51]=k[5],J(this,14,f,h,g)};
function O(a,b,c){b={url:b};a.qa&&(b.firstPartyDomain=null);browser.cookies.getAll(b,c)}function Q(a,b,c,d){(b=b[c])?(b=d?b.replace(/\./g,"\\.").replace(/\?/g,".").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"):b.replace(/\?/g,".").replace(/\*/g,".*"),b="^(?:"+b.replace(/\|{2,}/g,"|")+")$"):b="(?!)";a.c[c]=new RegExp(b,"i")}
function R(a,b,c,d,e,f,h,g){if(!d||a.c[-8]){var k=a.a[b];if(k){var m=Sa(a),n=m.b;m.tabId=b;m.port=k;m.j=c;m.a=0;m.l=[];if(k=d&&!!e)m.A=!0,m.u=e,m.g=f,m.h=h,m.zoom=g,e.a||S(a,e);e="^(?:http|https|ftp|ftps|rtmp|rtmpt|rtmpe|mms)://";d&&(d=a.c[12])&&(d=d.replace(/\./g,"\\."),d=d.replace(/\*/g,".*"),d=d.replace(/\~/g,"(?:.*\\.)?"),e=e+"(?:[^\\/]*@)?(?:"+d+")(?::\\d+)?(?:\\W|$)");m.f=T(a,b,[12,n,c,k,e]);m.v=0;m.f||I(a,n)}}}
l.I=function(a,b,c){if(4294967295==a)this.h=null,c=!0;else{var d=this.f[a];if(d){c=d.a;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:d.a=3;window.setTimeout(this.I.bind(this,a,!1,!0),1E3);return}d.a=0;c=!0}}c&&J(this,8,32,[a])};function Ua(a,b){var c=a.b[b];if(c&&c.P){var d=c.border,e=c.scale;J(a,7,0,[b,Math.round((c.V+d)*e),Math.round((c.ma+d)*e),Math.round((c.width-d-c.ja)*e),Math.round((c.height-d)*e)])}}
function Va(a,b,c,d){var e=a.f[b],f=256;2==e.a&&(d?(f|=128,e.a=1):f|=64);var h,g,k,m,n;c&&(h=c.left,g=c.top,k=c.right||h+1,m=c.bottom||g+1,n=c.zoom,c=e.port.f)&&(h+=c.left,g+=c.top,k=Math.min(k+c.left,c.right),m=Math.min(m+c.top,c.bottom));J(a,9,f,[b,h,g,k,m,n])}
l.T=function(a){var b=this.b,c=[];if(a)(a=b[a])&&(a.B||a.C||c.push(a.s));else for(var d in b)a=b[d],a.B||a.C||c.push(a.s);if(c.length){b=[15,null,null];a={};var e=this.f;for(d in e){var f=e[d];f.a&&0<=c.indexOf(f.port.tabId)&&(f.b?(f=f.port,f.a||S(this,f,null,a),b[2]=d,f.postMessage(b)):Va(this,d,null,!0))}}};function Wa(a,b){var c=a.b[b];c&&!c.C&&U(a,c.s,void 0)}function U(a,b,c){var d=c?0:2;c=c?32:64;var e=a.f,f;for(f in e){var h=e[f];h.a&&h.port.tabId==b&&h.a!=d&&(h.a=d,J(a,8,c,[f]))}}
function V(a,b,c,d){var e=a.N,f=(e&b)!=((c?63:32)&b);a.N=c?e|=b:e&=~b;f&&(c=a.c[-1],b=a.c[-2],c=a.M=0!=c&&(e&c)==c,e=a.Y=0!=b&&(e&b)==b,a.ra=(c||e)&&d||null)}l.na=function(a,b,c,d){var e=this.b[a];if(e)if(d)e.C&&window.clearTimeout(e.C),e.C=window.setTimeout(this.na.bind(this,a,b,c),d);else if(e.C=null,b&&(browser.windows.get(a,this.K),browser.tabs.query({windowId:a,active:!0},this.K)),c){if((a=this.b[a])&&!a.C){a=a.s;b=this.f;for(var f in b)c=b[f],c.a&&c.port.tabId==a&&1==c.a&&J(this,8,1152,[f])}}else this.T(a)};
l.K=function(a){a instanceof Array&&(a=a.shift());if(a){var b=a.windowId||a.id,c=this.b[b];if(c){var d=!!a.windowId;if(!(d&&c.ready&&sa.test(a.url))){if(d)c.s=a.id,a.width&&(c.la=a.width),a.height&&(c.ka=a.height);else{var d="fullscreen"==a.state,e=d!=c.B;c.B=d;c.Na="maximized"==a.state;c.za="minimized"==a.state;if(t){var f=c.scale;c.width=Math.round(a.width/f);c.height=Math.round(a.height/f);c.left=Math.round(a.left/f);c.top=Math.round(a.top/f)}else c.width=a.width,c.height=a.height,c.left=a.left,
c.top=a.top;e&&(d?Wa(this,b):this.T(b))}e=c.la;a=c.ka;if(e&&a){f=c.width;d=c.height;if(!c.ready&&!c.za){if(e>f||a>d)return browser.windows.get(b,this.K);c.ready=!0}e=f-e;f=e/2;20>=f?(c.border=f,c.V=c.ja=0):(f=c.border,w?c.V=e-2*f:c.ja=e-2*f);a=d-a-2*f;a<=ca&&(c.ma=a)}Ua(this,b)}}}};
function S(a,b,c,d){a=a.a;c=[16,c];for(var e=[b],f;f=a[b.c];b=f){if(d)if(d[b.id])break;else d[b.id]=!0;e.push(f)}for(f=e.pop();b=e.pop();f=b)d=b.Ma,c[2]=d,c[3]=b.frameId,c[4]=d?null:b.url,c[5]=d?null:b.F,f.postMessage(c)}function T(a,b,c){a=a.a;b=[b,null].toString();var d=0,e;for(e in a)e.startsWith(b)&&(a[e].postMessage(c),d++);return d}
l.R=function(a){function b(a){a;browser.runtime.lastError}var c={file:"content.js",runAt:"document_start",allFrames:!0};620756992<=this.j&&(c.matchAboutBlank=!0);if(a instanceof Array)for(;a.length;)try{browser.tabs.executeScript(a.shift().id,c,b)}catch(d){}else try{browser.tabs.executeScript(a.id||a,c,b)}catch(d){}};function Xa(a,b){"object"!=typeof b&&(b=a.b[b]);b&&null==b.P&&J(a,6,17,[b.id,0,b.width,b.height,b.left,b.top,b.scale])}l.ya=function(a){for(;a.length;)this.Ca(a.shift(),!0)};
l.ca=function(a,b){if(!this.u)return Ya(b.id,"cannot_contact_idm");var c=a.linkUrl,d=a.pageUrl;if(a.menuItemId==this.D[4])return browser.downloads.search({query:[c]},this.La.bind(this,c));if(a.menuItemId==this.D[1])c=a.frameUrl||d;else if(!c){var c=a.srcUrl,e=this.a[[b.id,a.frameId].toString()];if(e){var f=Sa(this);f.tabId=b.id;f.port=e;f.url=c;f.pageUrl=d;f.i=4;return e.postMessage([18,f.b,c])}}c&&this.S(c,d,4)};
l.wa=function(a,b){if(!this.u)return Ya(b.id,"cannot_contact_idm");R(this,b.id,a.menuItemId==this.D[2])};l.La=function(a,b){for(var c,d,e;c=b.pop();)c.exists&&"complete"==c.state?d||e||(e=c.referrer):(d||(d=c.referrer),browser.downloads.erase({id:c.id}));this.S(a,d||e,4)};
l.Ra=function(a){var b=a.sender.tab;if(b&&!(0>b.id)){var c=a.id;null==c&&(c=a.id=a.portId_||this.Ja++);var d=b.id,e="top"==a.name;a.tabId=d;a.windowId=0>b.index?null:b.windowId;a.g=!0;a.h=!1;a.a=e;a.frameId=e?0:a.sender.frameId;a.j=0;a.url=a.sender.url||e&&b.url||null;a.F=null;this.v[c]=a;e&&(this.a[d]=a);a.onMessage.addListener(this.Sa.bind(this,a));a.onDisconnect.addListener(this.ea);this.da(a)}};
l.ea=function(a,b){if(a.g){b||(a.g=!1);var c=this.f,d=this.g,e=this.l,f,h,g;for(g in c)if(f=c[g],f.port===a)f.a&&this.I(g),delete c[g];for(g in d)(h=d[g],h.port!==a||h.v)||(delete d[g],t&&delete d[h.id]);for(g in e)e[g].port===a&&delete e[g];this.ra===a&&V(this,63,!1);if(!b){c=a.tabId;d=a.frameId;e=[c,d].toString();f=this.i;for(g in f)e==f[g].b&&delete f[g];a.a&&delete this.a[c];delete this.a[[c,d]];delete this.v[a.id]}}};
l.Sa=function(a,b){switch(b[0]){case 21:var c=b[1];c&&(a.url=c,null==a.frameId&&this.da(a));break;case 22:var d=this.a,e=d[[a.tabId,b[2]]],c=b[4];e.Ma=b[3];e.f=c;if(d=d[e.c])if(d=d.f)c.left+=d.left,c.top+=d.top,c.right=Math.min(c.right+d.left,d.right),c.bottom=Math.min(c.bottom+d.top,d.bottom);break;case 23:var c=a.windowId,f=a.tabId,h=b[1],d=b[2],e=b[4],g=this.b[c];if(h){if(h=I(this,h)){var g=f==g.s&&!g.B,k=!d||!e;k&&(d=f);if(f=b[7])h[101]||h.J&&h.G&&h.J!=h.G||(h.J=f),h.G=f;var f=Ra(this,d,a,k?null:
b[5],k?null:b[6]),m=g&&!f.a;f.a=g?1:2;h instanceof D&&W(this,h,2,(g?128:64)|(k?512:0),c,d,h.J);k||(Va(this,d,e),m&&window.setTimeout(this.T.bind(this,c),3E3))}}else b[3]?(this.I(d,!0),delete this.f[d]):e&&f==g.s&&!g.B&&Va(this,d,e,!0);break;case 24:c=b[2];(d=this.l[b[1]])&&c&&(d[101]||d.J&&d.G&&d.J!=d.G||(d.J=c),d.G=c);break;case 25:Ra(this,b[1],a,b[2],b[3]);break;case 26:R(this,a.tabId,!0,!0,a,b[1],b[2],b[3]);break;case 27:if(c=this.l[b[1]]){d=c.l;if(e=b[4])if("string"==typeof e&&(e=JSON.parse(e)),
e instanceof Array){if(h=b[5])for(g=0;g<e.length;g++)e[g][4]=h;Array.prototype.push.apply(d,e)}b[3]&&(c.a+=b[3]);b[6]&&(c.pageUrl=b[6]);b[7]&&(c.G=b[7]);++c.v<c.f||(I(this,c.b),c.A?(d=this.b[c.port.windowId])&&d.s==c.tabId&&c.a&&(c.frame=c.u.f,e=c.zoom,h=d.border,g=d.scale,J(this,10,0,[4294967295,d.id,Math.round(c.g*e+(d.V+h)*g),Math.round(c.h*e+(d.ma+h)*g),0,c.a]),this.h=c.tabId,T(this,c.tabId,[13,!0])):d.length?this.Ga(d,c.j,c.D):Ya(c.tabId,"cannot_find_links"))}break;case 28:this.I(4294967295);
break;case 29:Za(this,a.windowId,a.tabId);break;case 30:Za(this,a.windowId,a.tabId,b[1],b[2]);break;case 31:(c=Ha[b[1]])&&V(this,c,b[2],a);break;case 32:0==b[1]&&V(this,32,b[2],a);break;case 33:V(this,63,!1);break;case 34:c=b[2];d=b[3];if(e=a.l||a.i)e=[e,c],h={},g=32,h[110]=b[1],h[115]=d,-2==c&&(g|=16),J(this,16,g,e,h);break;case 35:(c=I(this,b[1]))&&this.S(c.url,c.pageUrl,c.i,b[2],b[3])}};
l.Qa=function(a){var b=a.f,c=a.i,d=a.h,e=a.a,f;if(1==b){var h=e[0];if(f=this.H[h])b=f.f,delete this.H[h]}switch(b){case 3:var g=x[this.L%x.length];this.L=-1;this.Z=a[13]||"m"+e[2];4<=e[0]&&(this.pa="http://"+g+"/status/204+IDM");if(g=e[4]){g/=96;d=this.j;q&&(g=620756992>d?1:620756992<=d&&621284967>d?g:637534208<=d&&638078312>d?g:1.25<g?g:1);this.X=g;var g=this.b,d=this.X,k;for(k in g)e=g[k],e=[k,e.P,e.width,e.height,e.left,e.top,e.scale=d],J(this,6,17,e)}this.$&&this.aa();break;case 4:g=this.c;g[-9]=
0<(d&64);g[-8]=0<(d&32);g[-4]=0<(d&2);g[-11]=0<(d&256)||2>c;g[-12]=0<(d&512)||2>c;g[-1]=e[0];g[-2]=e[1];g[12]=a[12];Q(this,a,1);Q(this,a,2);Q(this,a,3);Q(this,a,4);Q(this,a,10);Q(this,a,9,!0);Q(this,a,11,!0);if(g=a[13])this.Z=g;Oa(this);this.O||(this.O=!0,q&&browser.browserAction.enable(),g=w?void 0:y,this.o(1,browser.runtime.onConnect,this.Ra),this.o(1,browser.webNavigation.onCommitted,this.Aa),this.o(1,browser.webNavigation.onHistoryStateUpdated,this.Pa),this.A?(this.o(2,browser.webRequest.onBeforeRequest,
this.ga,{urls:["*://*/*"],types:g},["requestBody","blocking"]),this.o(2,browser.webRequest.onBeforeSendHeaders,this.ha,{urls:["*://*/*"],types:g},["requestHeaders","blocking"]),this.o(2,browser.webRequest.onHeadersReceived,this.ia,{urls:["*://*/*"],types:g},["responseHeaders","blocking"])):(this.o(2,browser.webRequest.onBeforeRequest,this.ga,{urls:["http://*/*"],types:ka}),this.o(2,browser.webRequest.onBeforeRequest,this.ga,{urls:["https://*/*"],types:g},["requestBody","blocking"]),this.o(2,browser.webRequest.onBeforeSendHeaders,
this.ha,{urls:["http://*/*"],types:g},["requestHeaders"]),this.o(2,browser.webRequest.onBeforeSendHeaders,this.ha,{urls:["https://*/*"],types:g},["requestHeaders","blocking"]),this.o(2,browser.webRequest.onHeadersReceived,this.ia,{urls:["http://*/*"],types:g},["responseHeaders"]),this.o(2,browser.webRequest.onHeadersReceived,this.ia,{urls:["https://*/*"],types:g},["responseHeaders","blocking"])),this.o(3,browser.webRequest.onResponseStarted,this.$a,{urls:["<all_urls>"],types:g}),this.o(3,browser.webRequest.onErrorOccurred,
this.Za,{urls:["<all_urls>"],types:g}),this.o(3,browser.webRequest.onBeforeRequest,this.Ya,{urls:ta,types:ka},["blocking"]),browser.tabs.query({url:B[0]},this.R),browser.tabs.query({url:B[1]},this.R));break;case 5:g=e[0];(k=this.b[g])?(d=0!=(d&128),k.B!=d&&(k.B=d)&&Wa(this,g)):this.Da(g);break;case 6:if(d&4)break;g=f.a[0];k=e[1];if(d=this.b[g])d.P=k,Ua(this,g);break;case 8:g=e[0];k=d&32;if(4294967295==g)T(this,this.h,[13,!1]),this.h=null;else if(g=this.f[g])g.a=k?0:2;break;case 11:g=e[0];4294967295==
g&&(R(this,this.h,!0,!0),this.h=null);break;case 12:try{var m=a.a[5],n=a[4],g=4==m?2:3;if((1==m||2==m)&&Ta(this,a)){if(this.c[3].test(n))1==m?g=4:m=4;else if(this.c[-4]||this.c[4].test(n))g=4;a[8]|=256}if(4==m){switch(a.a[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}this.Fa(a)}else W(this,a,g)}catch(p){W(this,a,0)}break;case 13:k=f.a[0];d=f.a[5];e=e[1];if(1==d||2==d)X(this,k,null,3==e);else if(5==d)if(e){if(e=this.g[k]){k=e.i;d=e.requestHeaders;"POST"==e.method&&
(g=$a(e.f,Y(d,"Content-Type")));k.timeout=1E4;k.onreadystatechange=this.Ta.bind(this,k,e.id);k.open(g?"POST":"GET",e.url,!0);for(e=0;e<d.length;e++)a=d[e],c=a.name,0<=la.indexOf(c.toLowerCase())&&(c="X-IDM-"+c),k.setRequestHeader(c,a.value);k.send(g)}}else ab(this,k);break;case 1:break;default:!f&&d&1&&J(this,1,0,[a.g,0,0,0])}};
l.Fa=function(a,b,c){try{if(null==a.m)if(!b){var d=new L(this,a,!0);this.xa(a,null,d)||browser.windows.getLastFocused(M(d,2));if(d.c())return}else if(c){var e=this.b[c.id],f=this.a[e&&e.s];f&&(a.m=f.id)}f=this.v[a.m];if(!f)return W(this,a,0);var h;var g=a.b;g||(g=C.prototype.c++,a.b=g,this.l[g]=a);h=g;if(!f.a){var k=this.a[f.tabId];k&&k.postMessage([14,h])}var m=[15,h,null,a[6],a[17],a[50],a[31]];f.a||S(this,f,h);f.postMessage(m)}catch(n){W(this,a,0)}};
function W(a,b,c,d,e,f,h){-1!=c&&(e=[b.g,c,e,f],f={},f[8]=b[8],h&&(f[110]=h),J(a,1,d|(0==c?4:2),e,f))}l.Aa=function(a,b){var c=a.tabId,d=a.frameId,e=a.url,f=this.a[[c,d]];f?b?e!=f.url&&(f.url=e,f.j++,ua.test(e)&&(f.b=!0),this.ea(f,!0),f.postMessage([17,!1,f.b])):this.ea(f):0<d&&"about:blank"==e&&this.R(c)};l.Pa=function(a){return this.Aa(a,!0)};
l.Ca=function(a,b){var c=a.id,d={id:c,width:a.width,height:a.height,left:a.left,top:a.top,scale:this.X,border:8,ma:ba,V:0,ja:0,Na:"maximized"==a.state,za:"minimized"==a.state,B:"fullscreen"==a.state,ka:0,la:0,s:0,ready:!w,P:null,C:null};this.b[c]=d;browser.tabs.query({windowId:c,active:!0},this.K);browser.tabs.query({windowId:c,url:B[0]},this.R);browser.tabs.query({windowId:c,url:B[1]},this.R);b&&Xa(this,d)};l.Da=function(a){J(this,5,32,[a]);delete this.b[a]};
l.ab=function(a){if(0<a){var b=this.b[a];b&&(Xa(this,b),t&&this.na(a,!1,!0,500))}};l.Xa=function(a,b,c){var d=c.windowId,e=this.b[d];e&&(e.P||Xa(this,e),e.s||this.K(c));"complete"==b.status&&(a=this.a[a])&&!a.h&&(a.h=!0,this.T(d))};l.Va=function(a){this.N=0;this.h&&this.I(4294967295);var b=a.windowId;a=a.tabId;var c=this.a[a];c&&!c.windowId&&(c.windowId=b);if(c=this.b[b])U(this,c.s),c.s=a,browser.tabs.get(a,this.K),this.T(b)};
l.Wa=function(a,b){var c=b.newWindowId,d=this.v,e;for(e in d)(port=d[e])&&port.tabId==a&&(port.windowId=c);U(this,a,!0)};function Za(a,b,c,d,e){a.h&&a.I(4294967295);var f=a.b[b];f&&f.s==c&&(d&&(f.la=d),e&&(f.ka=e),U(a,c),a.na(b,d||e,!1,250))}function Z(a,b){var c=new XMLHttpRequest;a.i=c;c.responseType=b?"blob":"text";return!0}function ab(a,b){var c=a.g[b];if(c){var d=c.i;delete c.i;d&&d.abort();c.D&&X(a,c)}}
l.Ta=function(a,b){if(4==a.readyState){var c=[b,0],d={};200==a.status&&(d[115]=a.response);J(this,16,48,c,d);ab(this,b)}};function bb(a,b){if(b.g)return b.l=3,b.b|=2052,3;var c=a.c,d=new URL(b.url),e=cb(d.pathname);return e&&!d.search&&b.j&&c[2].test(e)?1:!w||!(a.A||b.a&128)||b.h||b.c||d.search||c[9].test(d.hostname)||!c[1].test(e)?4:(b.l=1,b.b|=8,5)}
function db(a,b){if(b.N)return a.sendRequest(b,6),1;var c=b.g,d=b.statusCode;if(!c&&200!=d&&206!=d)return 1;var e=a.c,f=b.url,d=b.c,h=Y(b.responseHeaders,"Content-Type"),g=Y(b.responseHeaders,"Content-Disposition"),k=eb(h).toLowerCase(),m="attachment"==eb(g).toLowerCase();if(!c){var n=b.j&&!m&&"text/html"==k;if(b.v)if(n){var p=a.i[[b.tabId,b.frameId]];p&&(p.c=!0);a.sendRequest(b,5)}else"application/json"==k&&(p=a.a[[b.tabId,b.frameId]])&&p.b&&(p.l=b.id,a.sendRequest(b,5));if(n)return 1}if(b.h||!d&&
!e[-9])return 1;var n=c,v=p=!1,f=new URL(f),u=f.hostname,r=f.pathname,E=fb(g,"filename")||fb(h,"name"),g=E&&cb(E),z=!1,h=!1;if(E)if(g||c)z=h=!0,b.fileName=E,b.A=g;else if(!d)return 1;h||(E=r.split("/").pop(),(g=cb(E))&&g.toLowerCase()==k.split("/").pop()&&(z=!0));if(!c){var ib=va.test(u);if(d&&ib)if(r==wa)p=z=!0;else if(r.startsWith(za)&&"text/xml"==k)v=!0;else{if(r.endsWith(xa)&&"application/x-www-form-urlencoded"==k||r.endsWith(ya)&&"application/x-www-form-urlencoded"==k||r.startsWith(Aa)&&"video/vnd.mpeg.dash.mpd"==
k)v=Z(b)}else if(d&&Ba.test(u))"M4S"==g&&(z=!0),u==Ca&&r.startsWith(Da)&&"application/json"==k&&(v=Z(b));else if(d&&Ea.test(u))if((u=Fa.exec(r))&&"application/x-javascript"==k)(r=Ga.exec(b.port.url))&&u[1]!=r[1]||(v=Z(b));else if(m&&"image"==b.type&&"MP4"==g)return 1;if(!z){if(u=Ja[k])if(u=u.split("|"),g&&0<=u.indexOf(g))z=!0;else if(d||!g)g=u.shift(),z=!0;if(!g&&!v)return 1;!g||z||!m&&k&&!e[10].test(k)||(z=!0);z&&(b.A=g)}d&&z&&("M3U8"==g||"F4M"==g?v=Z(b):"F4F"==g&&(E.endsWith("Seg1-Frag1")||E.endsWith("Seg1-Frag2")||
E.includes("Seg1-Frag2_"))&&(v=Z(b,!0)));if(d&&"ASF"==g&&((k=Y(b.responseHeaders,"Content-Length"))&&102400>=parseInt(k)||"DCLK-AdSvr"==Y(b.responseHeaders,"Server")))return 1;z&&(d&&e[3].test(g)?p=!0:!b.h&&e[1].test(g)&&(n=d?!e[-4]&&!e[4].test(g):!0))}if(!n&&!p&&!v||(e=p?e[11]:c?null:e[9])&&e.test(f.hostname))return 1;b.l=n?2:p?4:5;b.b|=c?2052:p||v?256:(d?4096:0)|(h||m?0:8388608)|16;b.L=v;return n?3:p?2:4}
l.sendRequest=function(a,b,c,d,e){var f=a.a,h=a.requestHeaders;if(1==(f&31)&&null==h){if(!d)return O(this,a.url,K(this,a,b,c,!0)),!0;"object"==typeof e&&(e=P(e))}null==b&&(b=a.l);null==c&&(c=0);var g=a.id,k=a.port&&a.port.id,m=a.timeStamp;d=a.responseHeaders;var n=a.H,p=a.b;f&64&&(p|=2097152);"POST"==a.method&&(p|=512);w&&4>b&&(c|=1);a.L&&(c|=a.i?17:16);a.c&&(c|=16);b=[g,k,Math.floor(m/1E3),Math.floor(m%1E3*1E3),f&31,b];f={};f[6]=gb(a.url);f[17]=a.F;f[4]=a.A;f[100]=a.fileName;f[8]=p;f[11]=hb(h);f[13]=
hb(d);f[18]=hb(n);a.f&&(f[14]=$a(a.f,Y(h,"Content-Type")));a.u&&(f[19]=$a(a.u,Y(n,"Content-Type")));null==h&&(f[50]=a.port&&a.port.url,f[51]=e,f[54]=navigator.userAgent);if(a=this.a[a.tabId])f[7]=a.url,f[110]=a.title;return J(this,13,c,b,f)};
function X(a,b,c,d){var e=a.g,f,h;"object"==typeof b?f=b.requestId:(f=b,b=e[f]);if(d)if(0>b.tabId)h={cancel:!0};else if(q&&c&&587202560>a.j)h=[{name:"Connection",value:"close"},{name:"Content-Type",value:"multipart/related"},{name:"Content-Length",value:"0"}],h={responseHeaders:h};else if(q||(w?c&&939524096>a.j:c)){h=a.pa;if(!h){h=pa;var g=a.i[[b.tabId,b.frameId]];g&&!g.f&&(h+="?back=1")}h={redirectUrl:h}}else h={cancel:!0};if(b){c&&c.ip&&(b.b|=c.ip.includes(":")?4194304:0);(c=b.resolve)&&void 0!==
d&&(b.resolve=b.reject=null,c(h||{}));if(d=b.reject)b.resolve=b.reject=null,d();!b.l||b.D||c||d||a.sendRequest(b);if(b.i)return b.D=!0,h;delete e[f];t&&delete e[b.id];b.c&&(e[b.id]={url:b.url,port:b.port})}return h}l.Ya=function(a){var b=a.url,c=new URL(b);if(c.search.startsWith("?d="))return a=this.a[a.tabId],this.S("idmreg:"+b.substr(c.protocol.length),a&&a.url),{redirectUrl:pa+"?register=1"}};
l.ga=function(a){if(!(w&&0>y.indexOf(a.type))){var b=a.tabId,c=a.frameId;if(!(0>b||0>c)){var d=a.requestId,e=a.url,f=N(e),h=a.type.endsWith("_frame"),g="POST"==a.method;if(h){var k;k=[b,c].toString();var m=this.i;k=k in m?m[k]:m[k]=new La(b,c,a.parentFrameId);k.a!=d&&(k.a=d,k.F=e,k.url=null,k.c=!1);k.f=g}if(this.A||f&128){e=this.M;k=this.Y;m=!0;if(!k&&g&&a.requestBody){var g=a.requestBody,n=g.raw;if(n)for(var p=0;p<n.length&&(n[p].bytes||(n=null));p++);n||g.formData||g.error?(d=this.g[d])?d.requestBody=
g:H(this,a):m=!1}if(e&&m)switch(a.a=f,a.f=a.requestBody,a.j=h,a.c=0<=A.indexOf(a.type),a.g=e,a.h=k,a.port=this.a[[b,c]],bb(this,a)){case 5:if(w)return new Promise(this.Ha.bind(this,a));case 3:return X(this,a,null,!0)}}}}};
l.ha=function(a){if(!(w&&0>y.indexOf(a.type))){var b=a.tabId;if(0<b){var c=a.requestId,d=a.url,e=a.method,f=N(d);if(!f||"GET"!=e&&"POST"!=e)return X(this,a);a.g=this.M;a.h=this.Y;if(c=this.g[c])a.id=c.id,a.port=c.port,a.f=c.requestBody,c.a&&(a.F=c.F||c.url,a.H=c.H||c.requestHeaders,a.u=c.u||c.f,a.g=c.g,a.h=c.h),!w||302!=c.statusCode&&303!=c.statusCode||(a.method=e="GET");var c=a.type,h=c.endsWith("_frame");if(!a.port&&!(a.port=this.a[[b,a.frameId]])&&!h||"POST"==e&&(!a.f||a.f.error&&0<Y(a.requestHeaders,
"Content-Length")))return X(this,a);d.includes("#")&&(a.url=gb(d));a.a=f;a.j=h;a.c=0<b&&0<=A.indexOf(c);a.v=ua.test(d);switch(bb(this,a)){case 5:if(w)return new Promise(this.Ha.bind(this,a));if(!a.g)break;case 3:return X(this,a,null,!0);case 1:return X(this,a)}H(this,a)}else if("xmlhttprequest"==a.type&&(a.M?a.M==qa:a.O?a.O==ra:1)){a=a.requestHeaders;b=[];for(e=d=0;e<a.length;e++)if(f=a[e],c=f.name,"Origin"!=c||f.value!=qa)c.startsWith("X-IDM-")&&(f.name=c.substr(6),d++),b.push(f);if(d)return{requestHeaders:b}}return null}};
l.Ha=function(a,b,c){a.resolve=b;a.reject=c;H(this,a);this.sendRequest(a)};
l.ia=function(a){if(!(w&&0>y.indexOf(a.type))){var b=this.g[a.requestId];if(b){var c=a.responseHeaders;if("image"==b.type){var d=Y(c,"Content-Type");if(d&&d.toLowerCase().startsWith("image/"))return X(this,b)}"quic"==Y(c,"Client-Protocol")?b.a|=64:(d=Y(c,"Alternate-Protocol"))&&d.endsWith(":quic,p=0")&&"chunked"!=Y(c,"Transfer-Encoding")&&(b.a|=64);if(this.A||b.a&192){var d=a.statusLine,e=parseInt(d.split(" ",2).pop());b.statusLine=d;b.statusCode=e;b.N=0<=ma.indexOf(e);b.responseHeaders=c;switch(db(this,
b)){case 3:return X(this,b,a,!0)}}}}};l.$a=function(a){if(!(w&&0>y.indexOf(a.type))){var b=this.g[a.requestId];if(b){if(b.j){var c=this.i[[b.tabId,b.frameId]];c&&(c.url=b.url)}X(this,b,a)}}};l.Za=function(a){w&&0>y.indexOf(a.type)||X(this,a.requestId)};
l.aa=function(a,b,c,d,e,f){if(void 0===a&&(this.$=!1,a=new L(this,!0),browser.storage.local.get("version",M(a,1)),(t?1073741824<=this.j:q)&&browser.extension.isAllowedIncognitoAccess(M(a,2)),q&&(browser.management.get(ha,M(a,3)),browser.management.get(ia,M(a,4))),aa&&browser.runtime.id!=ga&&browser.management.get(ga,M(a,5)),a.c()))return;a=browser.runtime.getManifest();a=a.version||"";"object"==typeof b&&(b=b.version||"");c=null!=c&&!c;"object"==typeof d&&(d=d.enabled&&d.id);d&&browser.management.setEnabled(d,
!1);"object"==typeof e&&(e=e.enabled&&e.id);e&&browser.management.setEnabled(e,!1);"object"==typeof f&&(f=f.enabled&&f.id);f&&browser.management.setEnabled(f,!1);a&&a!=b&&null!=b&&(browser.storage.local.set({version:a}),d=this.Z,f=d<(t?ea:w?fa:0),!b||!d||f||e)&&(a="current="+escape(a),b&&(a+="&previous="+escape(b)),c&&(a+="&incognito=1"),e&&(a+="&mulsrch=1"),d&&(a+="&manager="+escape(d)),f&&(a+="&update=1"),t&&(a+="&msedge=1"),w&&(a+="&mzffox=1"),aa&&(a+="&opera=1"),browser.tabs.create({url:browser.runtime.getURL("welcome.html?"+
a)}))};function Ya(a,b){var c=browser.i18n.getMessage(b);w?browser.tabs.executeScript(a,{code:'window.alert(unescape("'+escape(c)+'"))'}):window.alert(c)}l.o=function(a,b){var c=Array.prototype.slice.call(arguments);if(w||t){var d=c[2];c[2]=function(){return d.apply(null,arguments)}}this.sa.push(c);b.addListener.apply(b,c.slice(2))};function L(a){this.caller=arguments.callee.caller;this.f=a;this.b=Array.prototype.slice.call(arguments,1);this.a=0}function M(a,b){a.a++;return a.h.bind(a,b)}
L.prototype.c=function(){return this.a?(arguments.length&&(this.b=Array.prototype.slice.call(arguments)),!0):!1};L.prototype.h=function(a,b){browser.runtime.lastError;this.b[a]=b;0==--this.a&&this.caller.apply(this.f,this.b)};L.prototype.g=function(a,b,c){var d=Array.prototype.slice.call(arguments,3);c&&(d=c.concat(d));a.apply(b,d);this&&0==--this.a&&this.caller.apply(this.f,this.b)};
function K(a){var b=Array.prototype.slice.call(arguments,1),c=b[b.length-1];c instanceof L?c.a++:c=null;return L.prototype.g.bind(c,arguments.callee.caller,a,b)}function Qa(a){return browser.i18n.getMessage(a)||a}function gb(a){var b=a.lastIndexOf("#");return 0>b||b<a.indexOf("?")?a:a.substr(0,b)}function P(a){var b="";if(a&&a.length)for(var c=0;c<a.length;c++)b&&(b+="; "),b+=a[c].name,b+="=",b+=a[c].value;return b}
function hb(a){if(!a||!a.length)return null;for(var b="",c=0;c<a.length;c++)b+=a[c].name,b+=": ",b+=a[c].value,b+="\n";return b}function Y(a,b){if(!a)return null;b=b.toLowerCase();for(var c=0;c<a.length;c++)if(a[c].name.toLowerCase()==b)return a[c].value;return null}
function fb(a,b){if(!a)return null;var c=a.split(";");for(b=b.toLowerCase();c.length;){var d=c.shift(),e=d.indexOf("=");if(0<e){var f=d.substr(0,e).trim().toLowerCase(),h="*"==f[f.length-1];h&&(f=f.substr(0,f.length-1).trimRight());if(f==b)return c=d.substr(e+1).trim(),d=c.length-1,'"'==c[0]&&'"'==c[d]&&(c=c.substring(1,d)),h&&(c=c.split("'",3).pop()),unescape(c)}else if(0>e&&d.trim().toLowerCase()==b)return""}return null}
function eb(a){return a&&(a=a.split(";",1).shift().trim())&&0>a.indexOf("=")&&unescape(a)||""}
function $a(a,b){if(!a)return null;var c=a.raw;if(c){for(var d=String.fromCharCode,e="",f=0;f<c.length;f++){var h=c[f].bytes;if(!h)return null;for(var h=new Uint8Array(h),g=h.length,k=0;k<g;k++)e+=d(h[k])}return e}c=a.formData;if(!c)return null;f=eb(b).toLowerCase();e=[];if(f&&"application/x-www-form-urlencoded"!=f)if("multipart/form-data"==f){(h=fb(b,"boundary"))||(h="----WebKitFormBoundary"+Math.random().toString(36).substr(2));for(d in c)for(g=c[d],f=0;f<g.length;f++)e.push("--",h,'\r\nContent-Disposition: form-data; name="',
d,'"\r\n\r\n',g[f],"\r\n");e.push("--",h,"--\r\n")}else return null;else for(d in c)for(g=c[d],d=d.split(" ").map(encodeURIComponent).join("+"),f=0;f<g.length;f++)e.length&&e.push("&"),e.push(d,"=",g[f].split(" ").map(encodeURIComponent).join("+"));return e.join("")}function cb(a){return(a=oa.exec(a))?a.pop().toUpperCase():""}function N(a,b){var c=a.split("://",1).shift().toLowerCase(),c=Ia[c]||0;return b?c&31:c}
var Pa=[[!0,-11,"menu_download_link","link,image",G.prototype.ca],[!0,-11,"menu_download_link","page,frame",G.prototype.ca,B],[!0,-11,"menu_download_selected","selection",G.prototype.wa],[!0,-12,"menu_download_all","page,frame",G.prototype.wa],[q,-11,"menu_download_item","link",G.prototype.ca,["chrome://downloads/*"]]];String.prototype.startsWith||(String.prototype.startsWith=function(a,b){return this.substr(b||0,a.length)===a});
String.prototype.endsWith||(String.prototype.endsWith=function(a,b){b=(null==b||b>this.length?this.length:b)-a.length;return 0<=b&&this.lastIndexOf(a,b)==b});String.prototype.includes||(String.prototype.includes=function(a,b){return 0<=this.indexOf(a,b)});new G;
